// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>


const char THING_ID[] = "72c9880a-49d8-4daa-9916-3061debb65ac";

const char SSID[]     = SECRET_SSID;    // Network SSID (name)
const char PASS[]     = SECRET_PASS;    // Network password (use for WPA, or use as key for WEP)

void onMaxTempChange();
void onFanOnChange();
void onOverrideFanControlChange();

float max_temp;
float temperature;
bool fan_on;
bool override_fan_control;

void initProperties(){

  ArduinoCloud.setThingId(THING_ID);
  ArduinoCloud.addProperty(max_temp, READWRITE, ON_CHANGE, onMaxTempChange);
  ArduinoCloud.addProperty(temperature, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(fan_on, READWRITE, ON_CHANGE, onFanOnChange);
  ArduinoCloud.addProperty(override_fan_control, READWRITE, ON_CHANGE, onOverrideFanControlChange);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
